const bankpayRoute = require('express').Router()

const onepagegtest = require("../controller/singlepagegateways") 

bankpayRoute.post('/dnsPay',onepagegtest.dnsPay)
bankpayRoute.post('/dnspayment',onepagegtest.dnspayment)
bankpayRoute.post('/statusapidns',onepagegtest.statusapidns)
bankpayRoute.post('/dnsnetbank',onepagegtest.dnsnetbank)
bankpayRoute.post('/simPaisaCard',onepagegtest.simPaisaCard)
bankpayRoute.post('/simPaisaCardVerify',onepagegtest.simPaisaCardVerify)
bankpayRoute.post('/simPaisaWallet',onepagegtest.simPaisaWallet)
bankpayRoute.post('/simPaisaWalletVeify',onepagegtest.simPaisaWalletVeify)
bankpayRoute.post('/singlePayoutPayment',onepagegtest.singlePayoutPayment)
bankpayRoute.post('/h2hPayment',onepagegtest.h2hPayment)
bankpayRoute.post('/check',onepagegtest.check)
bankpayRoute.post('/flutterweb',onepagegtest.flutterweb)
bankpayRoute.post('/flutterwebss',onepagegtest.flutterwebss)
bankpayRoute.post('/flutterweb3d',onepagegtest.flutterweb3d)
bankpayRoute.post('/flutterweb3dhttp',onepagegtest.flutterweb3dhttp)
bankpayRoute.post('/convergeGate',onepagegtest.convergeGate)
bankpayRoute.post('/convergeGateStatus',onepagegtest.convergeGateStatus)
bankpayRoute.post('/piniklePSP',onepagegtest.piniklePSP)
bankpayRoute.post('/statusPinikle',onepagegtest.statusPinikle)
bankpayRoute.post('/transactpay',onepagegtest.transactpay)
bankpayRoute.post('/transactpayStatus',onepagegtest.transactpayStatus)
bankpayRoute.post('/pay_every',onepagegtest.pay_every)
bankpayRoute.post('/instaExchange',onepagegtest.instaExchange)
bankpayRoute.post('/checkUserStatusR',onepagegtest.checkUserStatusR)
bankpayRoute.post('/phpnibbl',onepagegtest.phpnibbl)
bankpayRoute.post('/caresPay',onepagegtest.caresPay)
bankpayRoute.post('/connPay',onepagegtest.connPay)
bankpayRoute.post('/instaXchange',onepagegtest.instaXchange)
// bankpayRoute.post('/aiApi',onepagegtest.aiApi)
bankpayRoute.post('/aronJCB',onepagegtest.aronJCB)
bankpayRoute.post('/callbackAronURl',onepagegtest.callbackAronURl)
bankpayRoute.post('/merchantPaymentStatusUpdateOnEndPoint',onepagegtest.merchantPaymentStatusUpdateOnEndPoint)
bankpayRoute.post('/patently',onepagegtest.patently)
bankpayRoute.post('/refundpatently',onepagegtest.refundpatently)
bankpayRoute.post('/fastPay',onepagegtest.fastPay)
bankpayRoute.post('/merchantPay',onepagegtest.merchantPay)
bankpayRoute.post('/readyPay',onepagegtest.readyPay)
bankpayRoute.post('/camlenio',onepagegtest.camlenio)
bankpayRoute.post('/fluterwave',onepagegtest.fluterwave)
bankpayRoute.post('/redipayStatus',onepagegtest.redipayStatus)
bankpayRoute.post('/payload_payport',onepagegtest.payload_payport)
bankpayRoute.post('/subPaisa',onepagegtest.subPaisa)
bankpayRoute.post('/subPaisaStatus',onepagegtest.subPaisaStatus)
bankpayRoute.post('/korapay',onepagegtest.korapay)
bankpayRoute.post('/korapaystatus',onepagegtest.korapaystatus)
bankpayRoute.post('/finic',onepagegtest.finic)
bankpayRoute.post('/ofapayout',onepagegtest.ofapayout)
bankpayRoute.post('/subvalixa',onepagegtest.subvalixa)

module.exports = bankpayRoute